Insert into PA_TAXGROUP_T (SEQ_NO_TG,SEQ_NO_PARAM,BU_CODE1,BU_TYPE1,BU_CODE2,BU_TYPE2,GA_CODE,GA_TYPE,VALID_FROM,VALID_TO,USERID,DELETE_DATE)
values (555555,5,'5100','COM','3310','COM','AU','CTY',to_date('01-SEP-11','DD-MON-RR'),null,'test',null);
