delete from CBD_BUSINESS_UNIT_T where SEQ_NO_BU='298045' and BU_CODE='278' and BU_TYPE='STO' and NAME='AL FUTTAIM TRADING COMPANY LLC';
delete from CBD_BUSINESS_UNIT_T where SEQ_NO_BU='298050' and BU_CODE='118' and BU_TYPE='STO' and NAME='IKEA CHEMNITZ';
delete from CBD_BUSINESS_UNIT_T where SEQ_NO_BU='298048' and BU_CODE='150' and BU_TYPE='STO' and NAME='IKEA COVENTRY';
