Insert into CBD_TAX_RATE_T (SEQ_NO_TR,GA_CODE,GA_TYPE,TAX_CODE,TAX_RATE,VALID_FROM,VALID_TO,IDRS_IMPORT_DATE,DELETE_DATE) values (5000004,'CA','CTY','9',5,to_date('27-OCT-04','DD-MON-RR'),null,to_date('11-FEB-15','DD-MON-RR'),null);
Insert into CBD_TAX_RATE_T (SEQ_NO_TR,GA_CODE,GA_TYPE,TAX_CODE,TAX_RATE,VALID_FROM,VALID_TO,IDRS_IMPORT_DATE,DELETE_DATE) values (5000003,'CAQC','STA','9',5,to_date('27-OCT-04','DD-MON-RR'),null,to_date('11-FEB-15','DD-MON-RR'),null);
update CBD_TAX_RATE_T set TAX_RATE=5 where SEQ_NO_TR=555555;
