Insert into CBD_CURRENCY_T (SEQ_NO_CUR,CUR_CODE,VALID_DECIMALS,ROUNDING_METHOD,VALID_FROM,VALID_TO,IDRS_IMPORT_DATE,DELETE_DATE) 
values (55555555,'EUR',3,'HALF_UP',to_date('01-JAN-90','DD-MON-RR'),null,to_date('18-NOV-14','DD-MON-RR'),null);
