-- Comment at start

CREATE TABLE ANIMALS (
  id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  color VARCHAR2(255) NOT NULL,
  name  VARCHAR2(255) NOT NULL
);

/* Block comment before insert */
INSERT INTO ANIMALS (color, name) VALUES ('brown', 'dog');
INSERT INTO ANIMALS (color, name) /* mid-statement block comment */ VALUES ('black', 'cat');
INSERT INTO ANIMALS (color, name) VALUES ('green', 'sloth');

-- Comment at end of
