potential-bugs:
  UnsafeCast:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
  DataClassContainsFunctions:
    active: false
  ExpressionBodySyntax:
    active: false
  MagicNumber:
    active: false
  UnnecessaryApply:
    active: false
  UseIfInsteadOfWhen:
    active: false
