failFast: true

potential-bugs:
  UnsafeCast:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
  FunctionMaxLength:
    active: false
  MagicNumber:
    active: false
  UnnecessaryApply:
    active: false
  VariableMinLength:
    minimumVariableNameLength: 2
  VariableMaxLength:
    active: false
