name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        java: [8, 11, 17]

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Build with Gradle
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build --stacktrace
      - name: Build with Gradle
        if: matrix.os == 'windows-latest'
        run: .\gradlew.bat build --stacktrace

      - name: Store reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports-${{ runner.os }}-${{ matrix.java }}
          path: build/reports
