name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        java: [ 8, 14, 16 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Setup Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle

      - name: Build with Gradle
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build --stacktrace
      - name: Build with Gradle
        if: matrix.os == 'windows-latest'
        run: .\gradlew.bat build --stacktrace

      - name: Store reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports-${{ runner.os }}-${{ matrix.java }}
          path: build/reports
