name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 25 ]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: "gradle"

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          package_json_file: html-report/package.json

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: html-report/.node-version
          cache: pnpm
          cache-dependency-path: html-report/pnpm-lock.yaml

      - name: Check
        run: ./gradlew check detektMain

      - name: Upload Gradle reports ${{ matrix.java }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          name: Gradle Reports
          path: "**/build/reports"

  verify-html-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          package_json_file: html-report/package.json

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: html-report/.node-version
          cache: pnpm
          cache-dependency-path: html-report/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: html-report
        run: pnpm install

      - name: Verify
        working-directory: html-report
        run: pnpm verify

      - name: Build
        working-directory: html-report
        run: pnpm build
