name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Set up Gradle cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches/modules-2
          key: ${{ runner.OS }}-gradle-

      - name: Build with Gradle
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build
      - name: Build with Gradle
        if: matrix.os == 'windows-latest'
        run: .\gradlew.bat build

      - name: Store reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports-${{ runner.OS }}
          path: build/reports
