name: CD

on:
  release:
    types: [ created ]

jobs:
  publish-maven-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          package_json_file: html-report/package.json

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: html-report/.node-version
          cache: pnpm
          cache-dependency-path: html-report/pnpm-lock.yaml

      - name: Setup JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: 17
          distribution: temurin
          cache: "gradle"

      - name: Publish
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.PUBLISH_SECRET }}
        env:
          GITHUB_VERSION: ${{ github.event.release.tag_name }}

      - name: Upload Gradle reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          name: Gradle Reports
          path: "**/build/reports"
